version: "3.9"

services:
  database:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: todo_list
      #MARIADB_USER: louan
      #MARIADB_PASSWORD: MARIADB_PASSWORD
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  go-test:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "8097:8080"
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_HOST=database:3306
      - DB_NAME=todo_list
    depends_on:
      database:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - 1333:8080

volumes:
  db_data:
